version: '3.8'

services:
  pi-go-openai-backend:
    container_name: go-openai-backend
    build: 
      context: .
      dockerfile: Dockerfile
    image: DOCKERHUB_USERNAME/go-openai:latest
    ports:
      - "8000:8000"
