apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-openai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-openai
  template:
    metadata:
      labels:
        app: go-openai
    spec:
      containers:
      - name: go-openai-container
        image: 16181181418/go-openai:latest
        ports:
        - containerPort: 8000  # Adjust this if your application uses a different port
        env:
        - name: OPENAI_API_KEY
          value: "111222333" 