apiVersion: v1
kind: Service
metadata:
  name: go-openai-service
spec:
  selector:
    app: go-openai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # Adjust this if your application uses a different port
      nodePort: 30000
  type: NodePort

