name: ci

on:
  push:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3 # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image tag in docker-compose.yml
        run: sed -i 's|DOCKER_USERNAME/go-openai:latest|${{ secrets.DOCKER_USERNAME }}/go-openai:latest|' docker-compose.yml

      - name: Build and push Docker image
        id: build-and-push
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

