name: ci

on:
  push:
    branches: [ "master" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3 # v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/go-openai:latest"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          docker-compose build

      - name: Tag Docker image
        run: |
          IMAGE_TAG="${{ env.IMAGE_TAG }}"
          docker tag go-openai:latest $IMAGE_TAG

      - name: Push Docker image
        run: |
          IMAGE_TAG="${{ env.IMAGE_TAG }}"
          docker push $IMAGE_TAG

